"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='mproxy',
    description='Mproxy',
    version='0.0.3',
    url='https://github.com/simonm3/mproxy.git',
    install_requires={'pandas', 'googletrans', 'requests', 'beautifulsoup4'},
    packages=['mproxy', 'mproxy.utils'],
    package_data={'mproxy': [
        'babies-first-names-top-100-girls.csv', 'server.yaml', 'tinyproxy.conf']},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
