"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='mproxy',
    description='Mproxy',
    version='0.0.5',
    url='https://github.com/simonm3/mproxy.git',
    install_requires=['apache_libcloud', 'fabric', 'googletrans',
                      'beautifulsoup4', 'pandas', 'requests', 'stem'],
    packages=['mproxy', 'mproxy.proxy', 'mproxy.source', 'mproxy.utils'],
    package_data={
        'mproxy/proxy': ['babies-first-names-top-100-girls.csv', 'tinyproxy.conf']},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
