"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='mproxy',
    description='Mproxy',
    version='0.0.3',
    url='https://github.com/simonm3/mproxy.git',
    install_requires=['googletrans', 'beautifulsoup4',
                      'requests', 'stem', 'pandas'],
    packages=['mproxy', 'mproxy.proxy', 'mproxy.utils'],
    package_data={'mproxy': ['server.yaml', 'tinyproxy.conf'],
                  'mproxy/proxy': ['babies-first-names-top-100-girls.csv']},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
